/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cabin(props) {
  const { nodes, materials } = useGLTF("/cabin.glb");
  return (
    <group {...props} dispose={null} position={[0,2,-20]} scale={0.5}>
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[0, 0.051, -23.983]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.884}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[-0.159, 4.251, -24.006]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={1.073}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[0, 1.419, -23.967]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.595}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[0, 2.613, -24.003]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.696}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[0.441, 6.049, -23.905]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.871}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[-0.088, 10.152, -23.86]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.652}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[0.194, 8.872, -23.901]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[-0.212, 7.526, -23.928]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.plank.geometry}
        material={nodes.plank.material}
        position={[12.947, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank001.geometry}
        material={nodes.plank001.material}
        position={[-0.355, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank002.geometry}
        material={nodes.plank002.material}
        position={[11.864, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank003.geometry}
        material={nodes.plank003.material}
        position={[-12.83, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank004.geometry}
        material={nodes.plank004.material}
        position={[-11.328, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank005.geometry}
        material={nodes.plank005.material}
        position={[-10.248, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank006.geometry}
        material={nodes.plank006.material}
        position={[-8.669, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank007.geometry}
        material={nodes.plank007.material}
        position={[-7.09, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank008.geometry}
        material={nodes.plank008.material}
        position={[-5.512, 0.849, -12.095]}
      />
      <mesh
        geometry={nodes.plank009.geometry}
        material={nodes.plank009.material}
        position={[-3.512, 0.849, -12.095]}
      />
      <mesh
        geometry={nodes.plank010.geometry}
        material={nodes.plank010.material}
        position={[-1.933, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank011.geometry}
        material={nodes.plank011.material}
        position={[1.647, 0.849, -12.045]}
      />
      <mesh
        geometry={nodes.plank012.geometry}
        material={nodes.plank012.material}
        position={[3.227, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank013.geometry}
        material={nodes.plank013.material}
        position={[4.307, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank014.geometry}
        material={nodes.plank014.material}
        position={[5.306, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank015.geometry}
        material={nodes.plank015.material}
        position={[6.387, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank016.geometry}
        material={nodes.plank016.material}
        position={[7.546, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.plank017.geometry}
        material={nodes.plank017.material}
        position={[9.127, 0.849, -12.045]}
      />
      <mesh
        geometry={nodes.plank018.geometry}
        material={nodes.plank018.material}
        position={[10.706, 0.849, -12.096]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[-13.921, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[-11.914, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[-9.911, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[-7.906, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={nodes.Cylinder019.material}
        position={[-5.903, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={nodes.Cylinder020.material}
        position={[-3.9, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={nodes.Cylinder021.material}
        position={[-1.898, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[0.104, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[2.111, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[4.117, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[6.123, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[8.123, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[10.13, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[12.139, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[14.149, 13.456, -18.931]}
        rotation={[1.175, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[14.14, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[12.133, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[10.13, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        position={[8.125, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        position={[6.122, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={nodes.Cylinder036.material}
        position={[4.119, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[2.117, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={nodes.Cylinder038.material}
        position={[0.115, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={nodes.Cylinder039.material}
        position={[-1.892, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={nodes.Cylinder040.material}
        position={[-3.898, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={nodes.Cylinder041.material}
        position={[-5.904, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={nodes.Cylinder042.material}
        position={[-7.904, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={nodes.Cylinder043.material}
        position={[-9.911, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={nodes.Cylinder044.material}
        position={[-11.92, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[-13.93, 13.389, -4.719]}
        rotation={[1.967, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, 0.051, 0.017]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.884}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0, 1.857, 0.044]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={1.073}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0, 3.41, 0.048]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.595}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0, 4.598, 0.035]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.696}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0, 6.057, -0.043]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.871}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[0, 7.464, 0.148]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.652}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[0, 8.739, -0.013]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[0, 10.076, 0.058]}
        rotation={[-0.393, 0, -Math.PI / 2]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[13.383, -0.034, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.884}
      />
      <mesh
        geometry={nodes.Cylinder047.geometry}
        material={nodes.Cylinder047.material}
        position={[13.307, 3.069, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={1.073}
      />
      <mesh
        geometry={nodes.Cylinder048.geometry}
        material={nodes.Cylinder048.material}
        position={[13.311, 4.618, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.595}
      />
      <mesh
        geometry={nodes.Cylinder049.geometry}
        material={nodes.Cylinder049.material}
        position={[13.391, 1.433, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.696}
      />
      <mesh
        geometry={nodes.Cylinder050.geometry}
        material={nodes.Cylinder050.material}
        position={[13.237, 7.183, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.871}
      />
      <mesh
        geometry={nodes.Cylinder051.geometry}
        material={nodes.Cylinder051.material}
        position={[13.256, 5.773, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.652}
      />
      <mesh
        geometry={nodes.Cylinder052.geometry}
        material={nodes.Cylinder052.material}
        position={[13.251, 8.657, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder053.geometry}
        material={nodes.Cylinder053.material}
        position={[13.139, 10.005, -11.818]}
        rotation={[-Math.PI / 2, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder054.geometry}
        material={nodes.Cylinder054.material}
        position={[13.139, 13.263, -11.818]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={nodes.Cylinder055.material}
        position={[13.139, 13.263, -10.472]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder056.geometry}
        material={nodes.Cylinder056.material}
        position={[13.139, 12.845, -9.124]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder057.geometry}
        material={nodes.Cylinder057.material}
        position={[13.139, 12.565, -7.816]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.685}
      />
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={nodes.Cylinder058.material}
        position={[13.139, 12.299, -6.669]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={nodes.Cylinder059.material}
        position={[13.139, 12.078, -5.481]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={nodes.Cylinder060.material}
        position={[13.139, 11.801, -4.291]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={nodes.Cylinder061.material}
        position={[13.139, 11.581, -3.1]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={nodes.Cylinder062.material}
        position={[13.139, 11.309, -1.912]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder063.geometry}
        material={nodes.Cylinder063.material}
        position={[13.139, 11.146, -0.721]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder064.geometry}
        material={nodes.Cylinder064.material}
        position={[13.139, 12.451, -16.529]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.685}
      />
      <mesh
        geometry={nodes.Cylinder065.geometry}
        material={nodes.Cylinder065.material}
        position={[13.139, 12.642, -15.382]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder066.geometry}
        material={nodes.Cylinder066.material}
        position={[13.139, 12.942, -14.194]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder067.geometry}
        material={nodes.Cylinder067.material}
        position={[13.139, 13.187, -13.004]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder068.geometry}
        material={nodes.Cylinder068.material}
        position={[13.139, 11.628, -20.458]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder069.geometry}
        material={nodes.Cylinder069.material}
        position={[13.139, 11.911, -19.11]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
      <mesh
        geometry={nodes.Cylinder070.geometry}
        material={nodes.Cylinder070.material}
        position={[13.139, 12.175, -17.802]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.685}
      />
      <mesh
        geometry={nodes.Cylinder071.geometry}
        material={nodes.Cylinder071.material}
        position={[13.139, 11.064, -22.998]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.552}
      />
      <mesh
        geometry={nodes.Cylinder072.geometry}
        material={nodes.Cylinder072.material}
        position={[13.139, 11.343, -21.81]}
        rotation={[-Math.PI, 1.178, 0]}
        scale={0.728}
      />
    </group>
  );
}
useGLTF.preload("/cabin.glb");
